name: TeamChunkClaimer
author: Cuuky
version: 0.1
softdepend: [CuukyFrameWork]
main: de.cuuky.teamchunkclaimer.Main

commands:
  chunk:
    description: Main Command for the chunks
    aliases: [chunks]
    
  team:
    description: Main Command for the teams
    aliases: [teams, factions, village]